resource_registry:
  OS::TripleO::ControllerDeployedServer::Net::SoftwareConfig: /usr/share/openstack-tripleo-heat-templates/net-config-static-bridge.yaml
  OS::TripleO::ComputeDeployedServer::Net::SoftwareConfig: /usr/share/openstack-tripleo-heat-templates/net-config-static.yaml
  OS::TripleO::DeployedServer::ControlPlanePort: /usr/share/openstack-tripleo-heat-templates/deployed-server/deployed-neutron-port.yaml
  OS::TripleO::Network::Ports::ControlPlaneVipPort: /usr/share/openstack-tripleo-heat-templates/deployed-server/deployed-neutron-port.yaml
  OS::TripleO::Network::Ports::RedisVipPort: /usr/share/openstack-tripleo-heat-templates/network/ports/noop.yaml


parameter_defaults:
  NeutronPublicInterface: eth1
  EC2MetadataIp: 192.168.24.1
  ControlPlaneDefaultRoute: 192.168.24.1
  DnsServers:
    - 10.5.30.160
  DeployedServerPortMap:
    osp11-controller-0-ctlplane:
      fixed_ips:
        - ip_address: 192.168.24.2
    osp11-controller-1-ctlplane:
      fixed_ips:
        - ip_address: 192.168.24.3
    osp11-controller-2-ctlplane:
      fixed_ips:
        - ip_address: 192.168.24.4
    osp11-compute-0-ctlplane:
      fixed_ips:
        - ip_address: 192.168.24.5
    control_virtual_ip:
      fixed_ips:
        - ip_address: 192.168.24.10
