resource_registry:
  OS::TripleO::Controller::Net::SoftwareConfig: /home/centos/tripleo-heat-templates/ci/common/net-config-multinode.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: /home/centos/tripleo-heat-templates/ci/common/net-config-multinode.yaml
