resource_registry:
  OS::TripleO::Compute::Net::SoftwareConfig: ../../../../tripleo-heat-templates/net-config-bridge.yaml

parameter_defaults:
  NeutronPublicInterface: eno3
  EC2MetadataIp: 192.168.24.1
  ControlPlaneDefaultRoute: 192.168.24.1
  DnsServers: []
  NtpServer: 0.centos.pool.ntp.org
