- name: Get Swift Account AUTH
  delegate_to: localhost
  shell: |
    source ~/stackrc
    openstack object store account show -f value -c Account
  register: swift_account_auth

- name: Get Swift Temp URL Key
  delegate_to: localhost
  shell: |
    source ~/stackrc
    openstack object store account show -f value -c properties | cut -d= -f2
  register: swift_tempurl_key

- name: Get Swift endpoint
  delegate_to: localhost
  shell: |
    source ~/stackrc
    openstack endpoint list --service swift --interface public -f value -c URL | awk -F'/v1' '{print $1}'
  register: swift_endpoint

- name: Generate Swift temporary metadata url
  delegate_to: localhost
  shell: |
    source ~/stackrc
    OS_AUTH_URL=${OS_AUTH_URL}/v3 swift tempurl GET {{ swift_tempurl_ttl }} /v1/{{ swift_account_auth.stdout }}/{{ swift_container_name }}/{{ inventory_hostname }} {{ swift_tempurl_key.stdout }}
  register: swift_metadata_url

- name: Set temporary metadata url fact
  set_fact:
    temporary_metadata_url: "{{ swift_endpoint.stdout + swift_metadata_url.stdout }}"

- name: Install openstack-heat-agents
  become: true
  package:
    name: openstack-heat-agents
    state: latest

- name: Copy Undercloud CA
  become: true
  copy:
    src: /etc/pki/ca-trust/source/anchors/cm-local-ca.pem
    dest: /etc/pki/ca-trust/source/anchors/cm-local-ca.pem
    owner: root
    group: root
    mode: 0644
  tags:
    - undercloud-ca

- name: Trust Undercloud CA
  become: true
  command: update-ca-trust extract
  tags:
    - undercloud-ca

- name: Create /var/lib/os-collect-config/local-data directory
  become: true
  file:
    path: /var/lib/os-collect-config/local-data
    state: directory

- name: Configure os-collect-config
  become: true
  template:
    src: templates/deployed-server.json.j2
    dest: /var/lib/os-collect-config/local-data/deployed-server.json

- name: Restart os-collect-config
  become: true
  service:
    name: os-collect-config
    enabled: yes
    state: restarted
