resource_registry:
  OS::TripleO::ControllerDeployedServer::Net::SoftwareConfig: tripleo-heat-templates/network/config/multiple-nics/controller.yaml
  OS::TripleO::ComputeDeployedServer::Net::SoftwareConfig: tripleo-heat-templates/network/config/multiple-nics/compute.yaml
  OS::TripleO::CephStorageDeployedServer::Net::SoftwareConfig: tripleo-heat-templates/network/config/multiple-nics/ceph-storage.yaml
  OS::TripleO::OpenShiftDeployedServer::Net::SoftwareConfig: tripleo-heat-templates/network/config/multiple-nics/openshift.yaml

parameter_defaults:
  # This section is where deployment-specific configuration is done
  # CIDR subnet mask length for provisioning network
  ControlPlaneSubnetCidr: '24'
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.168.24.1
  EC2MetadataIp: 192.168.24.1  # Generally the IP of the Undercloud
  ExternalInterfaceDefaultRoute: 192.168.24.1
  DnsServers:
    - 192.168.122.1
  NtpServer: clock.redhat.com
