resource_registry:
  OS::TripleO::Controller::Net::SoftwareConfig: ../../../tripleo-heat-templates/net-config-static-bridge.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: ../../../tripleo-heat-templates/net-config-static.yaml

parameter_defaults:
  NeutronPublicInterface: eth0
  EC2MetadataIp: 192.168.122.1
  ControlPlaneDefaultRoute: 192.168.122.1
  DnsServers:
    - 10.11.5.19
    - 10.10.160.2
    - 10.5.30.160
  NtpServer: clock.redhat.com
  CloudName: osp13-overcloud.localdomain
