---

- name: ssh-use-dns-no
  hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Set UseDNS=no
      lineinfile:
        state: present
        path: /etc/ssh/sshd_config
        line: UseDNS no
    - name: Restart sshd
      service:
       name: sshd
       state: restarted
