---

- name: tripleo-repos
  hosts: all
  tasks:
    - name: Run tripleo-repos
      shell: |
        rpm -q git || sudo yum -y install git python2-setuptools
        rpm -q python2-setuptools || sudo yum -y install python2-setuptools
        rpm -q python-requests || sudo yum -y install python-requests
        if [ ! -d tripleo-repos ]; then
          git clone https://git.openstack.org/openstack/tripleo-repos
        fi
        if ! which tripleo-repos; then
            pushd tripleo-repos
            sudo python setup.py install
            popd
        fi
        sudo tripleo-repos current-tripleo-dev
