resource_registry:
  OS::TripleO::ControllerOpenstack::Net::SoftwareConfig: ../../../tripleo-heat-templates/net-config-bridge.yaml
  OS::TripleO::ControllerPacemaker::Net::SoftwareConfig: ../../../tripleo-heat-templates/net-config-bridge.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: ../../../tripleo-heat-templates/net-config-static.yaml

parameter_defaults:
  NeutronPublicInterface: eth0
  EC2MetadataIp: 192.168.0.1
  ControlPlaneDefaultRoute: 192.168.0.1
  DnsServers: []
  NtpServer: 0.centos.pool.ntp.org
